/*
 * FLUENDO S.A.
 * Copyright (C) <2012>  <support@fluendo.com>
 */

#ifndef __GST_TTML_ENUMS_H__
#define __GST_TTML_ENUMS_H__

G_BEGIN_DECLS

/* Types of TTML nodes */
typedef enum _GstTTMLNodeType {
  GST_TTML_NODE_TYPE_UNKNOWN,
  GST_TTML_NODE_TYPE_P,
  GST_TTML_NODE_TYPE_SPAN,
  GST_TTML_NODE_TYPE_BR,
  GST_TTML_NODE_TYPE_SET,
  GST_TTML_NODE_TYPE_STYLING,
  GST_TTML_NODE_TYPE_STYLE
} GstTTMLNodeType;

/* Attributes currently supported */
typedef enum _GstTTMLAttributeType {
  GST_TTML_ATTR_NODE_TYPE,
  GST_TTML_ATTR_ID,
  GST_TTML_ATTR_BEGIN,
  GST_TTML_ATTR_END,
  GST_TTML_ATTR_DUR,
  GST_TTML_ATTR_TICK_RATE,
  GST_TTML_ATTR_FRAME_RATE,
  GST_TTML_ATTR_FRAME_RATE_MULTIPLIER,
  GST_TTML_ATTR_WHITESPACE_PRESERVE,
  GST_TTML_ATTR_SEQUENTIAL_TIME_CONTAINER,
  /* Only Styling attributes beyond this point! */
  GST_TTML_ATTR_STYLE,
  GST_TTML_ATTR_COLOR,
  GST_TTML_ATTR_BACKGROUND_COLOR,
  GST_TTML_ATTR_DISPLAY,
  GST_TTML_ATTR_FONT_FAMILY,
  GST_TTML_ATTR_FONT_STYLE,
  GST_TTML_ATTR_FONT_WEIGHT,
  GST_TTML_ATTR_TEXT_DECORATION
} GstTTMLAttributeType;

/* Event types */
typedef enum _GstTTMLEventType {
  GST_TTML_EVENT_TYPE_SPAN_BEGIN,
  GST_TTML_EVENT_TYPE_SPAN_END,
  GST_TTML_EVENT_TYPE_ATTR_UPDATE
} GstTTMLEventType;

/* Font Styles */
typedef enum _GstTTMLFontStyle {
  GST_TTML_FONT_STYLE_NORMAL,
  GST_TTML_FONT_STYLE_ITALIC,
  GST_TTML_FONT_STYLE_OBLIQUE
} GstTTMLFontStyle;

/* Font Weights */
typedef enum _GstTTMLFontWeight {
  GST_TTML_FONT_WEIGHT_NORMAL,
  GST_TTML_FONT_WEIGHT_BOLD
} GstTTMLFontWeight;

/* Text decorations (More than one can be selected) */
typedef enum _GstTTMLTextDecoration {
  GST_TTML_TEXT_DECORATION_NONE           = 0,
  GST_TTML_TEXT_DECORATION_UNDERLINE      = 1 << 0,
  GST_TTML_TEXT_DECORATION_STRIKETHROUGH  = 1 << 1,
  GST_TTML_TEXT_DECORATION_OVERLINE       = 1 << 2
} GstTTMLTextDecoration;

G_END_DECLS

#endif /* __GST_TTMLPRIVATE_H__ */
